version: '3'

services:
  node1:
    build: .
    ports:
      - "5001:5000"
    environment:
      - NODE_NAME=node1_1,node1_2,node1_3

  node2:
    build: .
    ports:
      - "5002:5000"
    environment:
      - NODE_NAME=node2_1,node2_2,node2_3

  node3:
    build: .
    ports:
      - "5003:5000"
    environment:
      - NODE_NAME=node3_1,node3_2,node3_3
