version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database_setup.py:/docker-entrypoint-initdb.d/database_setup.py
      - ./generate_records.py:/docker-entrypoint-initdb.d/generate_records.py
    mem_limit: 512m
    cpus: "0.5"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./database_setup.py:/docker-entrypoint-initdb.d/database_setup.py
      - ./generate_records.py:/docker-entrypoint-initdb.d/generate_records.py
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/testdb
    mem_limit: 1g
    cpus: "1.0"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@db:5432/testdb?sslmode=disable"
    ports:
      - "9187:9187"

volumes:
  grafana-storage:
