version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database_setup.py:/docker-entrypoint-initdb.d/database_setup.py
      - ./generate_records.py:/docker-entrypoint-initdb.d/generate_records.py
    mem_limit: 512m
    cpus: "0.5"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./database_setup.py:/docker-entrypoint-initdb.d/database_setup.py
      - ./generate_records.py:/docker-entrypoint-initdb.d/generate_records.py
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/testdb
    mem_limit: 1g
    cpus: "1.0"
