global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    metrics_path: /metrics
    params:
      format: ['prometheus']
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
